### PR TITLE
Record no-op operations, to fix repeated actions

### LINKED ISSUE #293: Repeated actions don’t repeat if the first action is a no-op
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

When a command usually changes behaviour when pressed multiple times, it does not work if the first command puts the window in the same place as it already is. For example, if the Move Right Command is pressed after pressing Right Half, nothing happens, even when Move Right is pressed repeatedly. Alternatively, if Rectangle is opened when a window already occupies the right-hand half of the screen, then the Right Half command will do nothing when pressed repeatedly, instead of cycling onto the next display.

A PR to fix is coming soon.

macOS version: 10.15.7
Rectangle version: master (c0949bbd4e19c417d351c4d053fb01779c83862e) (same behaviour on 0.40 (45))

### Logs

```
2020-12-12T17:05:32+01:00: AX sizing proposed: (1920.0, 788.0), result: (1920.0, 788.0)
2020-12-12T17:05:32+01:00: AX position proposed: (-1920.0, 492.0), result: (-1920.0, 492.0)
2020-12-12T17:05:32+01:00: AX sizing proposed: (1920.0, 788.0), result: (1920.0, 788.0)
2020-12-12T17:05:32+01:00: bottomRight | display: (-3840.0, 0.0, 3840.0, 1577.0), calculatedRect: (-1920.0, 492.0, 1920.0, 788.0), resultRect: (-1920.0, 492.0, 1920.0, 788.0), srcScreen: DELL U3818DW, destScreen: DELL U3818DW, resultScreen: DELL U3818DW
2020-12-12T17:05:34+01:00: Current frame is equal to new frame
2020-12-12T17:05:36+01:00: Current frame is equal to new frame
```

### Log explanation

- 2020-12-12T17:05:32+01:00: Bottom Right
- 2020-12-12T17:05:34+01:00: Move Right
- 2020-12-12T17:05:36+01:00: Move Right

### Configuration

``` sh
$ defaults read com.knollsoft.Rectangle
{
    "NSStatusItem Preferred Position Item-0" = 550;
    "NSWindow Frame SUUpdateAlert" = "714 648 620 392 0 0 2048 1257 ";
    "NSWindow Frame SUUpdateAlertSmall" = "-2230 1116 620 164 -3840 0 3840 1577 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2020-12-11 15:03:14 +0000";
    SUSendProfileInfo = 0;
    SUUpdateGroupIdentifier = 2260489891;
    SUUpdateRelaunchingMarker = 0;
    alternateDefaultShortcuts = 1;
    bottomCenterSixth = {length = 257, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 000000c7 };
    bottomLeft = {length = 257, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 000000c7 };
    bottomLeftSixth = {length = 257, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 000000c7 };
    bottomRight = {length = 257, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 000000c7 };
    bottomRightSixth = {length = 257, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 000000c7 };
    centerHalf = {length = 257, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 000000c7 };
    centeredDirectionalMove = 2;
    disabledApps = "[]";
    firstFourth = {length = 257, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 000000c7 };
    gapSize = 0;
    lastFourth = {length = 257, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 000000c7 };
    lastVersion = 45;
    launchOnLogin = 1;
    moveBottomHalf = {length = 135, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 0000005b };
    moveDown = {length = 257, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 000000c7 };
    moveLeft = {length = 257, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 000000c7 };
    moveRight = {length = 257, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 000000c7 };
    moveTopHalf = {length = 135, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 0000005b };
    moveUp = {length = 257, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 000000c7 };
    nextDisplay = {length = 257, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 000000c7 };
    previousDisplay = {length = 257, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 000000c7 };
    secondFourth = {length = 257, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 000000c7 };
    subsequentExecutionMode = 1;
    thirdFourth = {length = 257, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 000000c7 };
    topCenterSixth = {length = 257, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 000000c7 };
    topLeft = {length = 257, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 000000c7 };
    topLeftSixth = {length = 257, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 000000c7 };
    topRight = {length = 257, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 000000c7 };
    topRightSixth = {length = 257, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 000000c7 };
}
```

### PR DESCRIPTION
**Pull request by xsanda**
At the moment, `lastRectangleAction` is only updated when the operation caused the window to move. This means that, if an operation wouldn’t cause a move when it is first pressed, but instead only after a second press, then it actually has no effect on any subsequent press.

This PR fixes this, by updating `lastRectangleAction` explicitly when a move does not cause any effect.

Fixes #293

### CODE REVIEW

File: Rectangle/WindowManager.swift [hunk 1]
```diff
@@ -122,19 +142,7 @@ class WindowManager {
 
         let resultingRect = frontmostWindowElement.rectOfElement()
         
-        var newCount = 1
-        if lastRectangleAction?.action == calcResult.resultingAction,
-            let currentCount = lastRectangleAction?.count {
-            newCount = currentCount + 1
-            newCount %= 3
```
Comment (xsanda) [inline Rectangle/WindowManager.swift:129]: This modulo has been removed, because it duplicates the logic in [RepeatedExecutionsCalculation](https://github.com/rxhanson/Rectangle/blob/c0949bbd4e19c417d351c4d053fb01779c83862e/Rectangle/WindowCalculation/RepeatedExecutionsCalculation.swift#L31), and it could be problematic in future if repeated execution with another modulo is needed.

Comment (rxhanson) [reply Rectangle/WindowManager.swift:129]: Right, one of those things that I would think about but always forget to change.
